services:
  train:
    build: .
    container_name: rfdetr-iteracija1
    working_dir: /data/RT-DETR/iteracija1
    volumes:
      - ../../:/data
    command: python train.py
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    shm_size: "16g"
